INSERT INTO producto (categoria, descripcion, nombre, precio)
VALUES (2, 'Probás uno y no podés parar. Elaborados con fino polvo de almendras y viene en seis sabores: chocolate,
        limón, frutos del bosque, maracuyá, té matcha,
        queso mascarpone y chocolate blanco. El precio es por unidad y podemos llevarla a tu casa si pedís un mínimo de ocho macarons.',
        'Macarons', 350.00),
       (1, 'Bizcocho Sacher,
        mousse de chocolate al 70% de cacao. Bañada con glaseado al cacao y decorada con macaron relleno de ganache de chocolate y figuras de chocolate.',
        'Mini Mousse de chocolate', 1080.00),
       (1,
        'Masa sable breton rellena con nuestra untuosa crema de limón y terminado con el clásico merengue italiano.',
        'Mini Lemon Pie', 1080.00),
       (1, 'Interior de bizcocho soletilla, humedecido con almibar y licor de café,
        mousse de queso mascarpone. Cubierta con cacao y pedacitos de bizcocho.', 'Mini Tiramisú', 1080.00),
       (1, 'Masa de brownie con chocolate al 70% de cacao, nueces, dulce de leche y el clásico merengue Italiano.',
        'Mini Brownie', 1080.00),
       (1, 'Masa sable breton de chocolate rellena con crema pastelera y frutos del bosque.',
        'Mini Tarta de frutos del bosque', 1080.00),
       (0, 'Exquisitos budines de limón, limón y amapola, chocolate con dulce de leche, manzana con crumble,
        vainilla y maracuya, naranja, nuez y dulce de leche, chocolate y naranja, frutos del bosque.', 'Budines',
        1750.00),
       (1, 'Base de bizcocho de chocolate con polvo de almendras,
        un corte de mousse de chocolate al 70% de cacao y otro corte de mousse de sabayon. Cubierta con glaseado blanco,
        decorada con abanicos de chocolate.', 'Mini Mousse de Chocolate y Sabayón', 1080.00),
       (1, 'Base de masa sable breton rellena con crema pastelera y frutillas frescas.', 'Mini Tarta de Frutillas',
        1080.00),
       (1, 'Bizcocho de oliva y almendras, corazón de frutos del bosque, suave mousse de queso mascarpone.',
        'Mini Cheesecake', 1080.00),
       (2, 'Alfajores XL Ayulem: no vas a querer convidarle a nadie!', 'Alfajores XL', 610.00),
       (3, 'Torta de vainilla con relleno de crema chantilly y dulce de leche con un baño de ganache de chocolate,
        decorada con frutas, chocolate en rama y macarons', 'Torta de Cumple', 5980.00),
       (3, 'Bizcochuelo de vainilla, dulce de leche, duraznos, crema chantilly, trozos de merengue.', 'Balcarce',
        6050.00),
       (0, 'Copitos de dulce de leche bañados con chocolate. ¡Son increíbles y no vas a poder parar!',
        'Copitos de Dulce de Leche', 360.00),
       (0, 'Las masas secas de Ayulem tienen increíbles sabores y rellenos. Vienen pack de 1 kg.', 'Masas Secas',
        6000.00),
       (0, 'Palmeritas Ayulem – Riquísimas. Vienen en bolsitas de 1/4 kg. ¿Ya los probaste?', 'Palmeritas', 790.00),
       (0,
        'Masitas Húngaras Ayulem – Tienen una cubierta crocante de chocolate con almendras y están rellenas con dulce de frambuesas… ¡irresistibles! Vienen en paquete de 1/4 kg .',
        'Masitas Húngaras', 790.00),
       (1, 'Mousse de avellanas, interior de té matcha, bizcocho de nueces y lima,
        glaseado de chocolate blanco y té matcha. ¡Una exquisitez!', 'Mini Mousse de Avellanas', 1080.00),
       (0, 'Exquisitas Cookies Black Velvet por unidad.', 'Cookies XL', 390.00),
       (0, 'El Pan de Maíz Ayulem es un pan elaborado a base de harina de maíz, harina de trigo,
        pepitas de calabaza y abundante crema pastelera por fuera.', 'Pan de Maíz', 990.00),
       (3, 'La Tarta viene: con frutillas, arándanos y duraznos.
Base de masa sable con almendras fileteadas,
        crema catalana ligera y liviana saborizada con canela en rama y hebras de limón y frutillas o arándanos o duraznos.',
        'Tarta Catalana', 4590.00),
       (0, 'Si de clásicos reversionados se trata, estos scons lo son.', 'Scones', 790.00),
       (3,
        'Dacquoise de coco. Mousse de chocolate blanco. Cremoso de maracuyá en el interior. Cubierta con glaseado blanco.',
        'Mousse de Chocolate Blanco', 5160.00),
       (3, 'Suave bizcocho de chocolate y nueces, esponjoso de frutilla y cubierta con frutillas y arándanos.',
        'Esponjoso de Frutilla', 5160.00),
       (3,
        'Es una de las más antiguas del mundo. Es una delicia de origen austriaco. La masa está elaborada con polvo de almendras y especias dulces,
        y rellena de una confitura de frambuesas.', 'Tarta Linz', 3250.00),
       (1, 'Bizcocho de nuez,
        mousse de limón. Cubierta con un glasé de lima. Decorada con macarons de limón y bizcocho con nuez.',
        'Mini Mousse de Limón', 1080.00),
       (0, 'Pan navideño especiado super húmedo, relleno con almendras tostadas y naranjas confitadas,
        con corazón de pasta de almendras.', 'Stollen', 2900.00),
       (3, 'Bizcocho de avellanas, interior de pomelo rosado,
        mousse de chocolate con leche. Cubierta con un glaseado de chocolate con leche. Decorada con virutas de chocolate blanco.',
        'Mousse Black Velvet', 4730.00),
       (2, 'Alfajores sin TACC de chocolate blanco,
        negro o maicena. No son de elaboración propia porque no contamos en nuestra planta de elaboración de un espacio libre de gluten. Riquísimos!',
        'Alfajores Sin TACC', 690.00),
       (3, 'Bizcocho de vainilla con ganache de chocolate blanco y semiamargo, dulce de leche, crema de avellanas,
        crema de nougat y ganache de frambuesa, limón y maracuya. Lleva como decoraciones macarons, flores naturales,
        figuras de chocolate, frutos del bosque, frutillas, merenguitos y frutas secas', 'Torta de Letra',
        20500.00),
       (3, 'Masa sableé bretón de chocolate, crema de lima, cubierta de glaseado de chocolate blanco.',
        'Keylime Pie Ayulem', 4590.00),
       (3, 'Bizcochuelo de vainilla cubierta con butter cream blanco y rellena con crema bon o bon',
        'Naked Cake o Torta Desnuda', 11980.00),
       (0, 'Nuestros muffins son esponjosos y muy sabrosos de banana, frutos del bosque y chips de chocolate',
        'Muffins', 440.00),
       (1, 'Masa sableé bretón de vainilla, pastelera y frambuesas frescas.', 'Mini Tarta de Frambuesas', 1080.00);